# Generated by Django 5.2.17 on 2026-10-05 03:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre del caso')),
                ('razon_social', models.CharField(max_length=120, verbose_name='razón social')),
                ('ruc', models.CharField(blank=True, max_length=11, verbose_name='RUC')),
                ('simbolo_moneda', models.CharField(default='S/', max_length=5, verbose_name='símbolo de la moneda')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='inicio del período')),
                ('periodo_fin', models.DateField(blank=True, null=True, verbose_name='fin del período')),
                ('tasa_impuesto_renta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='tasa del impuesto a la renta (%)')),
                ('impuesto_afecta_patrimonio', models.BooleanField(default=False, help_text='Si se marca, el Balance General resta el impuesto del resultado del ejercicio. Sin marcar, el patrimonio muestra la utilidad antes de impuestos.', verbose_name='el impuesto a la renta afecta al patrimonio')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'caso',
                'verbose_name_plural': 'casos',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='número')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('glosa', models.CharField(blank=True, max_length=140, verbose_name='glosa')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='nucleo.caso')),
            ],
            options={
                'verbose_name': 'asiento',
                'verbose_name_plural': 'asientos',
                'ordering': ['fecha', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, verbose_name='código')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=12, verbose_name='tipo')),
                ('rubro', models.CharField(blank=True, choices=[('CORRIENTE', 'Corriente'), ('NO_CORRIENTE', 'No corriente'), ('VENTAS', 'Ventas'), ('DEVOLUCIONES_VENTAS', 'Devoluciones sobre ventas'), ('DESCUENTOS_VENTAS', 'Descuentos sobre ventas'), ('COSTO_VENTAS', 'Costo de ventas'), ('GASTO_VENTAS', 'Gasto de ventas'), ('GASTO_ADMINISTRACION', 'Gasto de administración'), ('INGRESO_FINANCIERO', 'Ingreso financiero'), ('GASTO_FINANCIERO', 'Gasto financiero'), ('OTRO_INGRESO', 'Otro ingreso'), ('OTRO_GASTO', 'Otro gasto')], max_length=24, verbose_name='clasificación')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='nucleo.caso')),
            ],
            options={
                'verbose_name': 'cuenta',
                'verbose_name_plural': 'cuentas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='LineaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='haber')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='nucleo.asiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='nucleo.cuenta')),
            ],
            options={
                'verbose_name': 'línea del asiento',
                'verbose_name_plural': 'líneas del asiento',
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='cuenta',
            constraint=models.UniqueConstraint(fields=('caso', 'codigo'), name='codigo_unico_por_caso'),
        ),
    ]
