# Generated by Django 5.2.17 on 2026-10-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_alter_lineaasiento_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='impuesto_afecta_patrimonio',
            field=models.BooleanField(default=True, help_text='Marcado (lo correcto): el patrimonio muestra la utilidad neta y el impuesto aparece como pasivo por pagar. Sin marcar, el patrimonio muestra la utilidad antes de impuestos y no se registra la deuda con SUNAT.', verbose_name='el impuesto a la renta afecta al patrimonio'),
        ),
    ]
