# Generated by Django 5.2.17 on 2026-10-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_impuesto_afecta_patrimonio_por_defecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='fecha')),
                ('consultas', models.PositiveIntegerField(default=0, verbose_name='consultas a la API')),
            ],
            options={
                'verbose_name': 'uso del asistente',
                'verbose_name_plural': 'uso del asistente',
                'ordering': ['-fecha'],
            },
        ),
    ]
